---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:7.1.3
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:7.1.3
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:7.1.3
  i386: ghcr.io/hassio-addons/ubuntu-base/i386:7.1.3
