---
name: Plex Media Server
version: dev
slug: plex
description: Recorded media, live TV, online news, and podcasts ready to stream.
url: https://github.com/hassio-addons/addon-plex
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:32400]/web
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armv7
map:
  - media:rw
  - share:rw
  - ssl
ports:
  3005/tcp: 3005
  8324/tcp: 8324
  32400/tcp: 32400
  32410/udp: 32410
  32412/udp: 32412
  32413/udp: 32413
  32414/udp: 32414
  32469/tcp: 32469
ports_description:
  3005/tcp: Plex Home Theater via Plex Companion
  8324/tcp: Plex for Roku via Plex Companion
  32400/tcp: Plex Media Server Interface
  32410/udp: GDM network discovery
  32412/udp: GDM network discovery
  32413/udp: GDM network discovery
  32414/udp: GDM network discovery
  32469/tcp: Plex DLNA Server
hassio_api: true
backup_exclude:
  - "**/Plex Media Server/Cache/**"
  - "**/Plex Media Server/Plug-in Support/Caches/**"
  - "**/Plex Media Server/Logs/**"
  - "**/Plex Media Server/Crash Reports/**"
  - "**/Plex Media Server/Diagnostics/**"
options:
  claim_code: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  claim_code: str
