#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Plex Media Server
# Runs the Plex Media Server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

hass.log.info 'Starting the Plex Media Server'

export LD_LIBRARY_PATH=/usr/lib/plexmediaserver
export PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver
export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
export PLEX_MEDIA_SERVER_INFO_DEVICE="Hass.io"
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/data

# Run the Plex Media Server
exec /usr/lib/plexmediaserver/Plex\ Media\ Server
